# SPDX-FileCopyrightText: 2023 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Jeremy Maceiras  <jeremy.maceiras@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only

exclude: "firmware"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: check-toml
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        types_or:
          - "c++"
          - "c"
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args: [--enable=all, --suppressions-list=.cppcheck-suppressions, --inline-suppr, --language=c++]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 7e1ceac2d5967f5428f0b1900cb7fe26da724bb1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, chore, ci, build] # optional: list of Conventional Commits types to allow
